### ISSUE TITLE
외부라이브러리가 cmake로 지원한다면, 본 빌드시스템 또한 cmake로 수정해야 할까요?

### ISSUE THREAD

**Issue by YoungjaeDev** [jacking75/examples_CMake#2]
안녕하세요
기존에 makefile로 시스템을 구성했는데, [xtensor](https://github.com/xtensor-stack/xtensor)와 같은 외부 라이브러리를 사용하려고 하는데
사용하게 된다면 아래 예제처럼 Cmake로 바꿔서 Link를 해주는 방법밖에 없나요?

https://github.com/jacking75/examples_CMake#07-helloworld---%EC%99%B8%EB%B6%80-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC%EC%97%AC%EA%B8%B0%EC%84%9C%EB%8A%94-boost-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0

**Comment by jacking75** [comment]
아닙니다. 외부 라이브러리는 꼭 CMake로 변경할 필요 없습니다.
xtensor을 사용하는 쪽의 CMake에서 xtensor의 (동적 혹은 정적)라이브러리와 헤더파일을 선언해주면 됩니다.

**Comment by YoungjaeDev** [comment]
@jacking75 
xtensor 같은 라이브러리를 사전에 dpkg나 cmake로 설치한 후에 해당 pkg-config 파일을 탐색해서 연결하면 된다는 말씀이시죠?

**Comment by jacking75** [comment]
네 맞습니다~

**Comment by YoungjaeDev** [comment]
@jacking75 

마지막으로 하나만 더 여쭙고 싶습니다
기존에 사용하는 프로젝트가 C++17로 빌드됩니다
그런데 추가하려는 xTensor는 C++14로 빌드가 된다고 나와있습니다
현재 사용하고 있는 프로젝트에 xTensor를 내장해서 API를 만드려고 하는데
그러면 제안받는 방법은 CMakeLists를 작성해야 하는데, 저는 도통 이해가 되지 않아서요
CMake 초보긴 하는데, 왜 그런지 배경을 알 수 있을까요?

**Comment by jacking75** [comment]
질문의 의도가 이해되지 않습니다.
왜 C++14, 17을 사용하느냐의 질문이라면 이것은 만드는 사람이 정한 것이라서 저도 왜 이렇게 하는지는 모릅니다^^;

**Comment by YoungjaeDev** [comment]
@jacking75 
네 감사합니다

**Comment by YoungjaeDev** [comment]
@jacking75 

보통 C++17가 C++14 빌드 호환이 되지 않나요?

**Comment by jacking75** [comment]
기능이 서로 다르니 C++17 기능을 C++14에서 사용 못하고, 라이브러리 부분이 정적 lib로 빌드 되었다면 서로 표준이 달라서 링크 에러가 날 수도 있습니다.
